package es.arrima.files;

/**
 * Where uploaded images live: Supabase Storage in production, a local folder in development.
 * Paths are always generated by the backend (see {@link StoredFilePaths}), never taken from the client.
 */
public interface FileStorage {

    void store(String path, byte[] content, String contentType);

    StoredFile load(String path);

    void delete(String path);
}
